controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# ------------------------
# Google OAuth2
# ------------------------
connect_google_start:
  path: /connect/google
  controller: App\Controller\OAuthController::connectGoogle

connect_google_check:
  path: /connect/google/check

# ------------------------
# Facebook OAuth2
# ------------------------
connect_facebook_start:
  path: /connect/facebook
  controller: App\Controller\OAuthController::connectFacebook

connect_facebook_check:
  path: /connect/facebook/check
# ------------------------
# Redirect After Login
# ------------------------
admin_dashboard:
  path: /admin/dashboard
  controller: App\Controller\AdminController::dashboard

user_dashboard:
  path: /profile/dashboard
  controller: App\Controller\UserController::dashboard

